#!/usr/bin/env bash
# This script loops indefinitely and traps SIGTERM

trap 'echo "I am invincible!!!"; exit' SIGTERM

while true; do
    echo "To infinity and beyond"
    # Sleep in the background and wait for it
    # This allows the shell to catch the trap immediately
    sleep 2 &
    wait $!
done
