#!/usr/bin/env bash
#I love her
echo $$ > /tmp/myscript.pid
 
cleanup() {
    echo "I hate the kill command"
    rm -f /tmp/myscript.pid
    exit 0
}
 
trap 'cleanup' SIGTERM SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT
 
while true; do
    echo "To infinity and beyond"
    sleep 2
done
